var myName = ("Waqas Ahmed")
var myAge = (24)
var message = ("Certified Web Application Developer")
var email = ("waqas01949@gmail.com")
var book = ("A smarter way to learn JavaScript")


alert(myName)
alert("I am "  + myAge + " Years old")
alert(message)
alert(email)
alert(myName + "\n" + "I am" + myAge + " Years old" + "\n" + message + "\n" + email)
alert("I am trying to learn from the Book " + book)
document.write("Yah! I can write HTML content through JavaScript")
alert("“▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬”")